"""initial_squash

Revision ID: c23e1bfb8824
Revises: 
Create Date: 2026-06-20 10:59:59.217581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c23e1bfb8824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_suffix', sa.String(length=8), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('degraded_reason', sa.String(length=40), nullable=True),
    sa.Column('degraded_until', sa.DateTime(), nullable=True),
    sa.Column('price_input_per_1m', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('price_output_per_1m', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('monthly_cost_limit', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('call_count_today', sa.Integer(), nullable=False),
    sa.Column('total_tokens_today', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_today', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('monthly_cost_used', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stats_date', sa.DateTime(), nullable=True),
    sa.Column('stats_month', sa.String(length=7), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encrypted_key', 'key_suffix', name='uq_api_secret_key')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_source'), 'knowledge_chunks', ['source'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('template_engine', sa.String(length=20), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_purpose'), 'prompt_templates', ['purpose'], unique=False)
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limit_key_ts', 'rate_limit_entries', ['key', 'created_at'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_max', sa.Integer(), nullable=False),
    sa.Column('raw_max', sa.Integer(), nullable=False),
    sa.Column('raw_scale', sa.Integer(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name')
    )
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['api_secrets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_id', 'purpose', name='uq_llmconfig_profile_purpose')
    )
    op.create_table('questionnaire_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_templates_school_id'), 'questionnaire_templates', ['school_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name')
    )
    op.create_table('case_questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('trigger_event', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['questionnaire_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'template_id', name='uq_cq_case_template')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id', 'name')
    )
    op.create_index('ix_classes_grade_id', 'classes', ['grade_id'], unique=False)
    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('training', 'assessment', 'free_play')", name='ck_practices_mode'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practices_case_id', 'practices', ['case_id'], unique=False)
    op.create_index('ix_practices_school_id', 'practices', ['school_id'], unique=False)
    op.create_table('questionnaire_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['questionnaire_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_questions_template_id'), 'questionnaire_questions', ['template_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission', name='ix_rp_role_perm')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('wechat_openid', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_school_id', 'users', ['school_id'], unique=False)
    op.create_index('ix_users_student_id', 'users', ['student_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_class', 'assignments', ['class_id'], unique=False)
    op.create_index('ix_assignments_practice', 'assignments', ['practice_id'], unique=False)
    op.create_index('ix_assignments_teacher', 'assignments', ['teacher_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created_at', 'feedbacks', ['created_at'], unique=False)
    op.create_index('ix_feedback_tag', 'feedbacks', ['tag'], unique=False)
    op.create_index('ix_feedback_user_id', 'feedbacks', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('qa_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_sessions_user_updated', 'qa_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_table('system_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('info', 'warning', 'success')", name='ck_sn_level'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_class_class_id', 'user_class', ['class_id'], unique=False)
    op.create_table('qa_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_records_created_at'), 'qa_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_qa_records_session_id'), 'qa_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_qa_records_user_id'), 'qa_records', ['user_id'], unique=False)
    op.create_index('ix_qa_session_created', 'qa_records', ['session_id', 'created_at'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=True),
    sa.Column('practice_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runtime_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scoring_status', sa.String(length=20), nullable=True),
    sa.Column('scoring_error', sa.Text(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('rubric_frozen', sa.String(length=80), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.CheckConstraint("current_phase IN ('history_taking', 'physical_exam', 'ending')", name='ck_training_records_current_phase'),
    sa.CheckConstraint("scoring_status IN ('pending', 'processing', 'completed', 'failed')", name='ck_training_records_scoring_status'),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name='ck_training_records_status'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='fk_training_records_case_id'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name='fk_training_records_practice_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_training_records_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tr_case_id', 'training_records', ['case_id'], unique=False)
    op.create_index('ix_tr_practice_id', 'training_records', ['practice_id'], unique=False)
    op.create_index('ix_tr_start_time', 'training_records', ['start_time'], unique=False)
    op.create_index('ix_tr_status', 'training_records', ['status'], unique=False)
    op.create_index('ix_tr_user_status', 'training_records', ['user_id', 'status'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('provider_name', sa.String(length=40), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('token_estimated', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('cost_currency', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_chars', sa.Integer(), nullable=True),
    sa.Column('response_chars', sa.Integer(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['llm_configs.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_case_id'), 'llm_call_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_config_id'), 'llm_call_logs', ['config_id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_created_at'), 'llm_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_error_type'), 'llm_call_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_latency_ms'), 'llm_call_logs', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_purpose'), 'llm_call_logs', ['purpose'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_record_id'), 'llm_call_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_status'), 'llm_call_logs', ['status'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_user_id'), 'llm_call_logs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('student', 'patient', 'system')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], name='fk_messages_record_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_msg_record_created', 'messages', ['record_id', 'created_at'], unique=False)
    op.create_index('ix_msg_role', 'messages', ['role'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_record_id', 'notes', ['record_id'], unique=False)
    op.create_table('nursing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sheet_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index('ix_nr_record_id', 'nursing_records', ['record_id'], unique=False)
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['questionnaire_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qr_record_id', 'questionnaire_responses', ['record_id'], unique=False)
    op.create_index('ix_qr_user_template', 'questionnaire_responses', ['user_id', 'template_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('detail_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('rubric_version', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('score_scale', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], name='fk_scores_record_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('scoring_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id'),
    sa.UniqueConstraint('record_id', name='uq_sp_record')
    )
    op.create_table('training_session_state',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('emotion_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('initiative_timer', sa.Float(), nullable=True),
    sa.Column('initiative_last_trigger', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('questionnaire_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['questionnaire_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_qa_response_question')
    )
    op.create_index(op.f('ix_questionnaire_answers_response_id'), 'questionnaire_answers', ['response_id'], unique=False)
    op.create_table('score_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('detail_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_id', name='uq_score_reviews_score_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_reviews')
    op.drop_index(op.f('ix_questionnaire_answers_response_id'), table_name='questionnaire_answers')
    op.drop_table('questionnaire_answers')
    op.drop_table('training_session_state')
    op.drop_table('scoring_progress')
    op.drop_table('scores')
    op.drop_index('ix_qr_user_template', table_name='questionnaire_responses')
    op.drop_index('ix_qr_record_id', table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    op.drop_index('ix_nr_record_id', table_name='nursing_records')
    op.drop_table('nursing_records')
    op.drop_index('ix_notes_record_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_msg_role', table_name='messages')
    op.drop_index('ix_msg_record_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_llm_call_logs_user_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_status'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_record_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_purpose'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_latency_ms'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_error_type'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_created_at'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_config_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_case_id'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index('ix_tr_user_status', table_name='training_records')
    op.drop_index('ix_tr_status', table_name='training_records')
    op.drop_index('ix_tr_start_time', table_name='training_records')
    op.drop_index('ix_tr_practice_id', table_name='training_records')
    op.drop_index('ix_tr_case_id', table_name='training_records')
    op.drop_table('training_records')
    op.drop_index('ix_qa_session_created', table_name='qa_records')
    op.drop_index(op.f('ix_qa_records_user_id'), table_name='qa_records')
    op.drop_index(op.f('ix_qa_records_session_id'), table_name='qa_records')
    op.drop_index(op.f('ix_qa_records_created_at'), table_name='qa_records')
    op.drop_table('qa_records')
    op.drop_index('ix_user_class_class_id', table_name='user_class')
    op.drop_table('user_class')
    op.drop_table('system_notifications')
    op.drop_index('ix_qa_sessions_user_updated', table_name='qa_sessions')
    op.drop_table('qa_sessions')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_feedback_user_id', table_name='feedbacks')
    op.drop_index('ix_feedback_tag', table_name='feedbacks')
    op.drop_index('ix_feedback_created_at', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index('ix_assignments_teacher', table_name='assignments')
    op.drop_index('ix_assignments_practice', table_name='assignments')
    op.drop_index('ix_assignments_class', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_student_id', table_name='users')
    op.drop_index('ix_users_school_id', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_questionnaire_questions_template_id'), table_name='questionnaire_questions')
    op.drop_table('questionnaire_questions')
    op.drop_index('ix_practices_school_id', table_name='practices')
    op.drop_index('ix_practices_case_id', table_name='practices')
    op.drop_table('practices')
    op.drop_index('ix_classes_grade_id', table_name='classes')
    op.drop_table('classes')
    op.drop_table('case_questionnaires')
    op.drop_table('roles')
    op.drop_index(op.f('ix_questionnaire_templates_school_id'), table_name='questionnaire_templates')
    op.drop_table('questionnaire_templates')
    op.drop_table('llm_configs')
    op.drop_table('grades')
    op.drop_table('cases')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_table('schools')
    op.drop_table('rubrics')
    op.drop_index('idx_rate_limit_key_ts', table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    op.drop_index(op.f('ix_prompt_templates_purpose'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_knowledge_chunks_source'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('api_secrets')
    # ### end Alembic commands ###
