"""drop_system_configs_table

Revision ID: 0a0515f13957
Revises: ec8f4a2b9d01
Create Date: 2026-06-22 16:18:07.838390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a0515f13957'
down_revision: Union[str, Sequence[str], None] = 'ec8f4a2b9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insp = inspect(op.get_bind())
    if "system_configs" in insp.get_table_names():
        op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
        op.drop_table('system_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insp = inspect(op.get_bind())
    if "system_configs" not in insp.get_table_names():
        op.create_table('system_configs',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('key', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('system_configs_pkey'))
        )
        op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    # ### end Alembic commands ###