"""add voice_configs and voice_call_logs

Revision ID: 0e4d42bd3540
Revises: mqo27fafw5eq
Create Date: 2026-06-22 13:01:23.134689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4d42bd3540'
down_revision: Union[str, Sequence[str], None] = 'mqo27fafw5eq'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vcl_created_at', 'voice_call_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vcl_created_at', table_name='voice_call_logs')
    # ### end Alembic commands ###
