"""add_initiative_count_to_training_session_state

Revision ID: 176306bda387
Revises: 0a0515f13957
Create Date: 2026-06-22 16:31:49.149596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176306bda387'
down_revision: Union[str, Sequence[str], None] = '0a0515f13957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_state', sa.Column('initiative_count', sa.Integer(), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_state', 'initiative_count')
    # ### end Alembic commands ###
