"""voice_config_v3

Revision ID: 1ac6b91b4c0b
Revises: 176306bda387
Create Date: 2026-06-22 20:40:51.610909

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "1ac6b91b4c0b"
down_revision: str | Sequence[str] | None = "176306bda387"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# new column -> (sqlalchemy type, server default for backfilling existing rows)
_NEW_COLUMNS: list[tuple[str, sa.types.TypeEngine, str]] = [
    ("api_key_enc", sa.Text(), ""),
    ("api_key_suffix", sa.String(length=8), ""),
    ("tts_resource_id", sa.String(length=64), "seed-tts-2.0"),
    ("tts_speaker", sa.String(length=64), "zh_female_vv_uranus_bigtts"),
    ("tts_model", sa.String(length=40), "seed-tts-2.0-standard"),
    ("tts_sample_rate", sa.Integer(), "24000"),
    ("tts_format", sa.String(length=16), "mp3"),
    ("asr_resource_id", sa.String(length=64), "volc.bigasr.sauc.duration"),
    ("asr_endpoint_mode", sa.String(length=24), "bigmodel_nostream"),
]

_DROPPED_COLUMNS = ["tts_voice_type", "token_enc", "asr_enable_streaming", "key_suffix", "app_id"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insp = inspect(op.get_bind())
    existing = {c["name"] for c in insp.get_columns("voice_configs")}

    for name, col_type, default in _NEW_COLUMNS:
        if name in existing:
            continue
        # Add with a server default so any existing row backfills, then drop the
        # default to keep the column in sync with the model (no server_default).
        op.add_column(
            "voice_configs",
            sa.Column(name, col_type, nullable=False, server_default=default),
        )
        op.alter_column("voice_configs", name, server_default=None)

    for name in _DROPPED_COLUMNS:
        if name in existing:
            op.drop_column("voice_configs", name)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insp = inspect(op.get_bind())
    existing = {c["name"] for c in insp.get_columns("voice_configs")}

    legacy = [
        ("app_id", sa.String(length=80), ""),
        ("token_enc", sa.Text(), ""),
        ("key_suffix", sa.String(length=8), ""),
        ("asr_enable_streaming", sa.Boolean(), sa.text("true")),
        ("tts_voice_type", sa.String(length=40), "zh_female_vv"),
    ]
    for name, col_type, default in legacy:
        if name in existing:
            continue
        op.add_column(
            "voice_configs",
            sa.Column(name, col_type, nullable=False, server_default=default),
        )
        op.alter_column("voice_configs", name, server_default=None)

    for name, _t, _d in reversed(_NEW_COLUMNS):
        if name in existing:
            op.drop_column("voice_configs", name)
    # ### end Alembic commands ###
