"""remove model column from llm_configs

Revision ID: 2ff501619763
Revises: 408e0352c5c1
Create Date: 2026-06-21 21:11:49.923292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff501619763'
down_revision: Union[str, Sequence[str], None] = '408e0352c5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('model', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
