"""add llm_call_logs cache tracking columns

Revision ID: 408e0352c5c1
Revises: 4dbaebd56173
Create Date: 2026-06-21 15:51:45.730228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408e0352c5c1'
down_revision: Union[str, Sequence[str], None] = '4dbaebd56173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call_logs', sa.Column('cache_hit_tokens', sa.Integer(), nullable=True))
    op.add_column('llm_call_logs', sa.Column('cache_miss_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call_logs', 'cache_miss_tokens')
    op.drop_column('llm_call_logs', 'cache_hit_tokens')
    # ### end Alembic commands ###
