"""drop_practice_mode_assessment

Revision ID: 4dbaebd56173
Revises: 09d519f18e4e
Create Date: 2026-06-21 15:15:50.111828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dbaebd56173'
down_revision: Union[str, Sequence[str], None] = '09d519f18e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practices', 'mode')
    op.drop_column('practices', 'assessment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('practices', sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
