"""add_rate_limit_entries

Revision ID: 53b07cf4d3b0
Revises: da319a6897a4
Create Date: 2026-06-19 15:47:16.320956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b07cf4d3b0'
down_revision: Union[str, Sequence[str], None] = 'da319a6897a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limit_key_ts', 'rate_limit_entries', ['key', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rate_limit_key_ts', table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    # ### end Alembic commands ###
