"""add rubric_frozen to training_records

Revision ID: a1b2c3d4e5f9
Revises: a1b2c3d4e5f8
Create Date: 2026-06-15
"""
# ### commands auto generated by Alembic
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "a1b2c3d4e5f9"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    insp = sa.inspect(conn)
    cols = [c["name"] for c in insp.get_columns("training_records")]

    if "rubric_frozen" not in cols:
        op.add_column("training_records", sa.Column("rubric_frozen", sa.String(80), nullable=True))


def downgrade() -> None:
    conn = op.get_bind()
    insp = sa.inspect(conn)
    cols = [c["name"] for c in insp.get_columns("training_records")]

    if "rubric_frozen" in cols:
        op.drop_column("training_records", "rubric_frozen")
