"""drop_api_provider_and_simplify_llm_config

Revision ID: ae8b50c13b08
Revises: 53b07cf4d3b0
Create Date: 2026-06-20 10:04:02.066016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae8b50c13b08'
down_revision: Union[str, Sequence[str], None] = '53b07cf4d3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_providers')
    op.drop_column('llm_configs', 'weight')
    op.drop_column('llm_configs', 'priority')
    op.drop_column('llm_configs', 'price_input_per_1m')
    op.drop_column('llm_configs', 'price_output_per_1m')
    op.drop_column('llm_configs', 'monthly_cost_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('monthly_cost_limit', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('price_output_per_1m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('price_input_per_1m', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('api_providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('api_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('default_model', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api_providers_pkey')),
    sa.UniqueConstraint('name', name=op.f('api_providers_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
