"""notification_record_id_fk_and_updated_at

Revision ID: c975c67840ab
Revises: mqqiqxnek37g
Create Date: 2026-06-23 18:46:52.662361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c975c67840ab'
down_revision: Union[str, Sequence[str], None] = 'mqqiqxnek37g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(
        'fk_notifications_record_id', 'notifications', 'training_records',
        ['record_id'], ['id'], ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_record_id', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'updated_at')
    # ### end Alembic commands ###
