"""llm_config_model_override

Revision ID: ca33908908b3
Revises: ae7285a8c73c
Create Date: 2026-07-15 17:27:46.391123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca33908908b3'
down_revision: Union[str, Sequence[str], None] = 'ae7285a8c73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('model_override', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'model_override')
    # ### end Alembic commands ###
