"""drop_multitenancy_schema

Revision ID: d7bf73a4fd58
Revises: mqwitf9lk76h
Create Date: 2026-06-27 23:35:04.206387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7bf73a4fd58"
down_revision: str | Sequence[str] | None = "mqwitf9lk76h"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FK constraints first (they reference schools)
    op.drop_constraint(op.f("cases_school_id_fkey"), "cases", type_="foreignkey")
    op.drop_constraint(op.f("grades_school_id_fkey"), "grades", type_="foreignkey")
    op.drop_constraint(op.f("practices_school_id_fkey"), "practices", type_="foreignkey")
    op.drop_constraint(op.f("questionnaire_templates_school_id_fkey"), "questionnaire_templates", type_="foreignkey")
    op.drop_constraint(op.f("roles_school_id_fkey"), "roles", type_="foreignkey")
    op.drop_constraint(op.f("users_school_id_fkey"), "users", type_="foreignkey")

    # Drop indexes on school_id columns
    op.drop_index(op.f("ix_practices_school_id"), table_name="practices")
    op.drop_index(op.f("ix_questionnaire_templates_school_id"), table_name="questionnaire_templates")
    op.drop_index(op.f("ix_users_school_id"), table_name="users")

    # Drop old UNIQUE(school_id, name) and create UNIQUE(name) for roles & grades
    op.drop_constraint(op.f("roles_school_id_name_key"), "roles", type_="unique")
    op.drop_constraint(op.f("grades_school_id_name_key"), "grades", type_="unique")

    # Drop school_id columns
    op.drop_column("cases", "school_id")
    op.drop_column("grades", "school_id")
    op.drop_column("practices", "school_id")
    op.drop_column("questionnaire_templates", "school_id")
    op.drop_column("roles", "school_id")
    op.drop_column("users", "school_id")

    # Create new UNIQUE(name) constraints
    op.create_unique_constraint("uq_roles_name", "roles", ["name"])
    op.create_unique_constraint("uq_grades_name", "grades", ["name"])

    # Drop schools table last (after all FKs + columns are gone)
    op.drop_table("schools")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schools",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("schools_pkey")),
        sa.UniqueConstraint(
            "name", name=op.f("schools_name_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )

    # Add school_id columns back (nullable=True to allow adding before populating with data)
    op.add_column("users", sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("roles", sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("questionnaire_templates", sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("practices", sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("grades", sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("cases", sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True))

    # Drop new UNIQUE(name) and restore old UNIQUE(school_id, name)
    op.drop_constraint("uq_roles_name", "roles", type_="unique")
    op.drop_constraint("uq_grades_name", "grades", type_="unique")
    op.create_unique_constraint(
        op.f("roles_school_id_name_key"), "roles", ["school_id", "name"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("grades_school_id_name_key"), "grades", ["school_id", "name"], postgresql_nulls_not_distinct=False
    )

    # Recreate indexes on school_id
    op.create_index(op.f("ix_users_school_id"), "users", ["school_id"], unique=False)
    op.create_index(op.f("ix_practices_school_id"), "practices", ["school_id"], unique=False)
    op.create_index(
        op.f("ix_questionnaire_templates_school_id"), "questionnaire_templates", ["school_id"], unique=False
    )

    # Recreate FK constraints
    op.create_foreign_key(op.f("users_school_id_fkey"), "users", "schools", ["school_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key(op.f("roles_school_id_fkey"), "roles", "schools", ["school_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        op.f("questionnaire_templates_school_id_fkey"),
        "questionnaire_templates",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("practices_school_id_fkey"), "practices", "schools", ["school_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(op.f("grades_school_id_fkey"), "grades", "schools", ["school_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(op.f("cases_school_id_fkey"), "cases", "schools", ["school_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###
