"""add_training_session_state

Revision ID: da319a6897a4
Revises: a1b2c3d4e6f0
Create Date: 2026-06-19 15:17:18.307296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da319a6897a4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session_state',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('emotion_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('initiative_timer', sa.Float(), nullable=True),
    sa.Column('initiative_last_trigger', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_session_state')
    # ### end Alembic commands ###
