"""add assignments table

Revision ID: e4350c414d9d
Revises: f5ec5b8f8a44
Create Date: 2026-06-10 14:25:51.642458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4350c414d9d'
down_revision: Union[str, Sequence[str], None] = 'f5ec5b8f8a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if "assignments" not in insp.get_table_names():
        op.create_table('assignments',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('config_id', sa.String(length=50), nullable=False),
        sa.Column('feature_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_assignments_case', 'assignments', ['case_id'], unique=False)
        op.create_index('ix_assignments_class', 'assignments', ['class_id'], unique=False)
        op.create_index('ix_assignments_teacher', 'assignments', ['teacher_id'], unique=False)
    cols = [c["name"] for c in insp.get_columns("training_records")]
    if "assignment_id" not in cols:
        op.add_column('training_records', sa.Column('assignment_id', sa.String(length=36), nullable=True))
    if "is_overdue" not in cols:
        op.add_column('training_records', sa.Column('is_overdue', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Don't recreate FK if it already exists
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('training_records_assignment_id_fkey', 'training_records', type_='foreignkey')
    op.drop_column('training_records', 'is_overdue')
    op.drop_column('training_records', 'assignment_id')
    op.drop_index('ix_assignments_teacher', table_name='assignments')
    op.drop_index('ix_assignments_class', table_name='assignments')
    op.drop_index('ix_assignments_case', table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
