"""add created_at to system_configs and training_session_state

Revision ID: ea1e2eacaf13
Revises: 2ff501619763
Create Date: 2026-06-22 01:26:59.246565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1e2eacaf13'
down_revision: Union[str, Sequence[str], None] = '2ff501619763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('training_session_state', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session_state', 'created_at')
    op.drop_column('system_configs', 'created_at')
    # ### end Alembic commands ###
