"""add key_suffix to voice_configs

Revision ID: ec8f4a2b9d01
Revises: ea1e2eacaf13
Create Date: 2026-06-22 03:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'ec8f4a2b9d01'
down_revision: Union[str, Sequence[str], None] = '0e4d42bd3540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    insp = inspect(op.get_bind())
    columns = [c["name"] for c in insp.get_columns("voice_configs")]

    if "key_suffix" not in columns:
        op.add_column(
            "voice_configs",
            sa.Column("key_suffix", sa.String(length=8), nullable=False, server_default=""),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_configs", "key_suffix")
    # ### end Alembic commands ###
