"""nursing_record_sheet_data

Revision ID: f5ec5b8f8a44
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 12:27:18.934362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ec5b8f8a44'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    cols = [c["name"] for c in insp.get_columns("nursing_records")]
    if "sheet_data" not in cols:
        op.add_column('nursing_records', sa.Column('sheet_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    if "assessment" in cols:
        op.drop_column('nursing_records', 'assessment')
    if "subjective" in cols:
        op.drop_column('nursing_records', 'subjective')
    if "plan" in cols:
        op.drop_column('nursing_records', 'plan')
    if "objective" in cols:
        op.drop_column('nursing_records', 'objective')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    cols = [c["name"] for c in insp.get_columns("nursing_records")]
    if "objective" not in cols:
        op.add_column('nursing_records', sa.Column('objective', sa.TEXT(), autoincrement=False, nullable=True))
    if "plan" not in cols:
        op.add_column('nursing_records', sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True))
    if "subjective" not in cols:
        op.add_column('nursing_records', sa.Column('subjective', sa.TEXT(), autoincrement=False, nullable=True))
    if "assessment" not in cols:
        op.add_column('nursing_records', sa.Column('assessment', sa.TEXT(), autoincrement=False, nullable=True))
    if "sheet_data" in cols:
        op.drop_column('nursing_records', 'sheet_data')
    # ### end Alembic commands ###
