"""add qa_records

Revision ID: 0e19cd74505c
Revises: 6e47092875f4
Create Date: 2026-05-30 14:01:07.596343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e19cd74505c'
down_revision: Union[str, Sequence[str], None] = '6e47092875f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_records_created_at'), 'qa_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_qa_records_user_id'), 'qa_records', ['user_id'], unique=False)
    op.create_index('ix_qa_user_created', 'qa_records', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qa_user_created', table_name='qa_records')
    op.drop_index(op.f('ix_qa_records_user_id'), table_name='qa_records')
    op.drop_index(op.f('ix_qa_records_created_at'), table_name='qa_records')
    op.drop_table('qa_records')
    # ### end Alembic commands ###
