"""data_model_overhaul_ddl — create tables, add/drop columns, indexes, constraints

# Autogenerated from models.py diff — DO NOT EDIT BY HAND.
# Data population and NOT NULL enforcement are in the companion data migration.

Revision ID: 1754404d9f59
Revises: merge_heads_20260610
Create Date: 2026-06-12 18:15:53.826809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1754404d9f59'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_20260610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ── New tables ──

    op.create_table('practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode IN ('training', 'assessment', 'free_play')", name='ck_practices_mode'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practices_case_id', 'practices', ['case_id'], unique=False)
    op.create_index('ix_practices_school_id', 'practices', ['school_id'], unique=False)

    op.create_table('score_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('detail_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_reviews_score_id', 'score_reviews', ['score_id'], unique=False)

    # ── Assignment changes ──

    op.add_column('assignments', sa.Column('practice_id', sa.Integer(), nullable=True))
    op.create_index('ix_assignments_practice', 'assignments', ['practice_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'practices', ['practice_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('assignments_case_id_fkey', 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_case'), table_name='assignments')
    op.drop_column('assignments', 'feature_overrides')
    op.drop_column('assignments', 'config_id')
    op.drop_column('assignments', 'case_id')

    # ── TrainingRecord changes ──

    op.add_column('training_records', sa.Column('practice_id', sa.Integer(), nullable=True))
    op.add_column('training_records', sa.Column('practice_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_tr_practice_id', 'training_records', ['practice_id'], unique=False)
    op.create_foreign_key('fk_training_records_practice_id', 'training_records', 'practices', ['practice_id'], ['id'])
    op.drop_column('training_records', 'config_snapshot')
    op.drop_column('training_records', 'config_id')

    # ── Cases ──

    op.add_column('cases', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ── Grades ──

    op.add_column('grades', sa.Column('academic_year', sa.String(length=9), nullable=True))

    # ── Messages ──

    op.create_index('ix_msg_role', 'messages', ['role'], unique=False)

    # ── Scores: drop review columns ──

    op.drop_column('scores', 'reviewed_by')
    op.drop_column('scores', 'review_status')
    op.drop_column('scores', 'reviewed_at')
    op.drop_column('scores', 'review_comment')
    op.drop_column('scores', 'review_detail_scores')

    # ── UserClass ──

    op.add_column('user_class', sa.Column('id', sa.Integer(), nullable=True))

    # ── Users ──

    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_users_school_id', 'users', ['school_id'], unique=False)
    op.create_index('ix_users_student_id', 'users', ['student_id'], unique=False)

    # ── CHECK constraints ──

    op.create_check_constraint(
        'ck_training_records_status',
        'training_records',
        "status IN ('in_progress', 'completed', 'abandoned')",
    )
    op.create_check_constraint(
        'ck_training_records_scoring_status',
        'training_records',
        "scoring_status IN ('pending', 'processing', 'completed', 'failed')",
    )
    op.create_check_constraint(
        'ck_training_records_current_phase',
        'training_records',
        "current_phase IN ('history_taking', 'physical_exam', 'ending')",
    )
    op.create_check_constraint(
        'ck_messages_role',
        'messages',
        "role IN ('student', 'patient', 'system')",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_student_id', table_name='users')
    op.drop_index('ix_users_school_id', table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_column('user_class', 'id')
    op.add_column('training_records', sa.Column('config_id', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('training_records', sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('fk_training_records_practice_id', 'training_records', type_='foreignkey')
    op.drop_index('ix_tr_practice_id', table_name='training_records')
    op.drop_column('training_records', 'practice_snapshot')
    op.drop_column('training_records', 'practice_id')
    op.add_column('scores', sa.Column('review_detail_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('review_comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('review_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ix_msg_role', table_name='messages')
    op.drop_column('grades', 'academic_year')
    op.drop_column('cases', 'updated_at')
    op.add_column('assignments', sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assignments', sa.Column('config_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('assignments', sa.Column('feature_overrides', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_case_id_fkey'), 'assignments', 'cases', ['case_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_assignments_practice', table_name='assignments')
    op.create_index(op.f('ix_assignments_case'), 'assignments', ['case_id'], unique=False)
    op.drop_column('assignments', 'practice_id')
    op.drop_index('ix_score_reviews_score_id', table_name='score_reviews')
    op.drop_table('score_reviews')
    op.drop_index('ix_practices_school_id', table_name='practices')
    op.drop_index('ix_practices_case_id', table_name='practices')
    op.drop_table('practices')
    # ### end Alembic commands ###
