"""api_management

Revision ID: 5c12378db675
Revises: 0e19cd74505c
Create Date: 2026-05-30 18:33:58.623614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c12378db675'
down_revision: Union[str, Sequence[str], None] = '0e19cd74505c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=200), nullable=False),
    sa.Column('api_type', sa.String(length=20), nullable=False),
    sa.Column('default_model', sa.String(length=80), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_suffix', sa.String(length=8), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_input_per_1m', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('price_output_per_1m', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('monthly_cost_limit', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('call_count_today', sa.Integer(), nullable=False),
    sa.Column('total_tokens_today', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_today', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stats_date', sa.Date(), nullable=True),
    sa.Column('monthly_cost_used', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stats_month', sa.String(length=7), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['api_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'purpose', name='uq_key_purpose')
    )
    op.alter_column('llm_call_logs', 'provider', new_column_name='provider_name',
                    existing_type=sa.String(length=40), existing_nullable=False)
    op.add_column('llm_call_logs', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_llm_call_logs_api_key_id'), 'llm_call_logs', ['api_key_id'], unique=False)
    op.create_foreign_key('llm_call_logs_api_key_id_fkey', 'llm_call_logs', 'api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('llm_call_logs_api_key_id_fkey', 'llm_call_logs', type_='foreignkey')
    op.drop_index(op.f('ix_llm_call_logs_api_key_id'), table_name='llm_call_logs')
    op.drop_column('llm_call_logs', 'api_key_id')
    op.alter_column('llm_call_logs', 'provider_name', new_column_name='provider',
                    existing_type=sa.String(length=40), existing_nullable=False)
    op.drop_table('api_key_rules')
    op.drop_table('api_keys')
    op.drop_table('api_providers')
    # ### end Alembic commands ###
