"""add_prompt_templates

Revision ID: b390fe86e625
Revises: c8390b049135
Create Date: 2026-05-31 00:55:08.486419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b390fe86e625'
down_revision: Union[str, Sequence[str], None] = 'c8390b049135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('template_engine', sa.String(length=20), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_purpose'), 'prompt_templates', ['purpose'], unique=False)
    op.create_index("idx_pt_purpose", "prompt_templates", ["purpose"])
    op.create_index("idx_pt_purpose_active", "prompt_templates", ["purpose", "is_active"])
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_llm_call_logs_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_index(op.f('ix_training_records_id'), table_name='training_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_training_records_id'), 'training_records', ['id'], unique=False)
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_id'), 'llm_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.drop_index("idx_pt_purpose_active", table_name="prompt_templates")
    op.drop_index("idx_pt_purpose", table_name="prompt_templates")
    op.drop_index(op.f('ix_prompt_templates_purpose'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
