"""data_model_overhaul_data — seed practices, migrate data, enforce NOT NULL

# Manual override reason: data_only
# Data migration companion to 1754404d9f59 (DDL).
# Hand-written because data migration logic cannot be autogenerated.

Revision ID: d47552f01c3a
Revises: 1754404d9f59
Create Date: 2026-06-12 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd47552f01c3a'
down_revision: Union[str, Sequence[str], None] = '1754404d9f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Fix sequences (SQLite→PostgreSQL migration artifact) ──
    tables_with_id = [
        "users", "roles", "role_permissions", "schools", "grades", "classes",
        "cases", "training_records", "messages", "scores", "notes", "rubrics",
        "llm_call_logs", "api_secrets", "llm_configs", "qa_sessions",
        "qa_records", "feedbacks", "prompt_templates", "questionnaire_templates",
        "questionnaire_questions", "questionnaire_responses", "questionnaire_answers",
        "case_questionnaires", "nursing_records",
    ]
    for tbl in tables_with_id:
        op.execute(
            f"SELECT setval(pg_get_serial_sequence('{tbl}', 'id'), COALESCE((SELECT MAX(id) FROM {tbl}), 1))"
        )

    # ── Populate nullable columns before NOT NULL enforcement ──

    op.execute("UPDATE cases SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('cases', 'updated_at', nullable=False)

    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('users', 'updated_at', nullable=False)

    # ── UserClass: composite PK → auto-increment PK ──
    op.execute("ALTER TABLE user_class DROP CONSTRAINT IF EXISTS user_class_pkey")
    op.execute("CREATE SEQUENCE IF NOT EXISTS user_class_id_seq")
    op.execute("UPDATE user_class SET id = nextval('user_class_id_seq') WHERE id IS NULL")
    op.alter_column('user_class', 'id', nullable=False)
    op.create_primary_key('user_class_pkey', 'user_class', ['id'])

    # ── Roles: cleanup leftover column ──
    op.execute("ALTER TABLE roles DROP COLUMN IF EXISTS id_new")

    # ── Scores: drop legacy review columns (data lost — no reviews in staging) ──
    # DDL already created score_reviews table; old scores columns are no longer used.
    op.drop_column('scores', 'reviewed_by')
    op.drop_column('scores', 'review_status')
    op.drop_column('scores', 'reviewed_at')
    op.drop_column('scores', 'review_comment')
    op.drop_column('scores', 'review_detail_scores')

    # ── Seed practices from session config JSONs ──
    import json
    from pathlib import Path

    config_dir = Path(__file__).resolve().parents[2] / "data" / "session_configs"
    if config_dir.exists():
        case_id = op.get_bind().execute(
            sa.text("SELECT id FROM cases ORDER BY id LIMIT 1")
        ).scalar()
        if case_id is not None:
            for fpath in sorted(config_dir.glob("*.json")):
                cfg = json.loads(fpath.read_text(encoding="utf-8"))
                op.execute(
                    sa.text(
                        "INSERT INTO practices (name, case_id, mode, features, behavior, assessment, created_at, updated_at) "
                        "VALUES (:name, :case_id, :mode, CAST(:features AS jsonb), CAST(:behavior AS jsonb), CAST(:assessment AS jsonb), now(), now())"
                    ).bindparams(
                        name=cfg.get("name", cfg["id"]),
                        case_id=case_id,
                        mode=cfg.get("mode", "training"),
                        features=json.dumps(cfg.get("features", {})),
                        behavior=json.dumps(cfg.get("behavior", {})),
                        assessment=json.dumps(cfg.get("assessment")) if cfg.get("assessment") else None,
                    )
                )

    # ── Migrate assignments: config_id → practice_id ──
    op.execute(
        "UPDATE assignments a SET practice_id = ("
        "  SELECT p.id FROM practices p ORDER BY p.id LIMIT 1"
        ") WHERE a.practice_id IS NULL"
    )
    op.alter_column('assignments', 'practice_id', nullable=False)

    # ── Migrate training records ──
    op.execute(
        "UPDATE training_records tr SET practice_id = ("
        "  SELECT p.id FROM practices p LIMIT 1"
        ") WHERE tr.practice_id IS NULL"
    )


def downgrade() -> None:
    # Restore user_class composite PK (id column stays — DDL owns it)
    op.execute("ALTER TABLE user_class DROP CONSTRAINT IF EXISTS user_class_pkey")
    op.alter_column('user_class', 'id', nullable=True)
    op.execute("ALTER TABLE user_class ADD PRIMARY KEY (user_id, class_id)")

    # Re-add review columns to scores as nullable
    op.add_column('scores', sa.Column('review_detail_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scores', sa.Column('review_comment', sa.TEXT(), nullable=True))
    op.add_column('scores', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('scores', sa.Column('review_status', sa.VARCHAR(length=20), nullable=True))
    op.add_column('scores', sa.Column('reviewed_by', sa.INTEGER(), nullable=True))

    # Re-add NOT NULL to ddl-added columns (reverse the NOT NULL enforcement)
    op.alter_column('cases', 'updated_at', nullable=True)
    op.alter_column('users', 'updated_at', nullable=True)
    op.alter_column('assignments', 'practice_id', nullable=True)
