"""initial_pg

Revision ID: e223ef76d97e
Revises: 
Create Date: 2026-05-29 17:27:46.160699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e223ef76d97e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scoring_status', sa.String(length=20), nullable=True),
    sa.Column('scoring_error', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tr_status', 'training_records', ['status'], unique=False)
    op.create_index('ix_tr_user_status', 'training_records', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_training_records_id'), 'training_records', ['id'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('token_estimated', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('cost_currency', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_chars', sa.Integer(), nullable=True),
    sa.Column('response_chars', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_case_id'), 'llm_call_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_created_at'), 'llm_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_error_type'), 'llm_call_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_id'), 'llm_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_latency_ms'), 'llm_call_logs', ['latency_ms'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_purpose'), 'llm_call_logs', ['purpose'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_record_id'), 'llm_call_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_status'), 'llm_call_logs', ['status'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_user_id'), 'llm_call_logs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index('ix_msg_record_created', 'messages', ['record_id', 'created_at'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('detail_scores', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('missed_content', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('rubric_version', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('score_scale', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_detail_scores', sa.JSON(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['training_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_msg_record_created', table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_llm_call_logs_user_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_status'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_record_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_purpose'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_latency_ms'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_error_type'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_created_at'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_case_id'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index(op.f('ix_training_records_id'), table_name='training_records')
    op.drop_index('ix_tr_user_status', table_name='training_records')
    op.drop_index('ix_tr_status', table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
