"""add feedbacks table

Revision ID: fb86a23a8928
Revises: b390fe86e625
Create Date: 2026-05-31 16:39:00.029750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb86a23a8928'
down_revision: Union[str, Sequence[str], None] = 'b390fe86e625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created_at', 'feedbacks', ['created_at'], unique=False)
    op.create_index('ix_feedback_tag', 'feedbacks', ['tag'], unique=False)
    op.create_index('ix_feedback_user_id', 'feedbacks', ['user_id'], unique=False)
    op.create_index('idx_api_keys_purpose', 'api_keys', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_keys_purpose', table_name='api_keys')
    op.drop_index('ix_feedback_user_id', table_name='feedbacks')
    op.drop_index('ix_feedback_tag', table_name='feedbacks')
    op.drop_index('ix_feedback_created_at', table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
