import type { RecordSheetConfig } from "./types";

export const NURSING_RECORD_SHEET_CONFIG: RecordSheetConfig = {
	title: "护理问诊记录单",
	sections: [
		{
			key: "general_survey",
			label: "一般情况评估",
			icon: "Eye",
			collapsible: true,
			items: [
				{
					key: "consciousness",
					type: "select",
					label: "意识状态",
					options: ["", "清醒", "嗜睡", "昏睡", "昏迷"],
					placeholder: "请选择",
					required: true,
				},
				{
					key: "nutrition",
					type: "radio",
					label: "营养状况",
					options: ["良好", "中等", "不良"],
					required: true,
				},
				{
					key: "mobility",
					type: "select",
					label: "活动能力",
					options: ["", "自如", "需协助", "卧床", "制动"],
					placeholder: "请选择",
				},
				{
					key: "communication",
					type: "radio",
					label: "沟通能力",
					options: ["清晰", "含糊", "失语", "不合作"],
				},
				{
					key: "facial_expression",
					type: "select",
					label: "面容表情",
					options: ["", "正常", "痛苦", "淡漠", "焦虑"],
					placeholder: "请选择",
				},
			],
		},
		{
			key: "vital_signs",
			label: "生命体征",
			icon: "Activity",
			collapsible: true,
			items: [
				{
					key: "vitals",
					type: "vital_sign",
					label: "生命体征",
					required: true,
				},
			],
		},
		{
			key: "respiratory",
			label: "呼吸系统评估",
			icon: "Wind",
			collapsible: true,
			items: [
				{
					key: "breath_rhythm",
					type: "select",
					label: "呼吸节律",
					options: ["", "规则", "不规则", "潮式呼吸"],
					placeholder: "请选择",
				},
				{
					key: "cough",
					type: "checkbox_group",
					label: "咳嗽",
					options: [
						{ key: "none", label: "无咳嗽" },
						{ key: "dry", label: "干咳" },
						{ key: "wet", label: "湿咳" },
						{ key: "paroxysmal", label: "阵发性" },
						{ key: "persistent", label: "持续性" },
						{ key: "night_worse", label: "夜间加重" },
					],
					columns: 3,
				},
				{
					key: "sputum",
					type: "checkbox_group",
					label: "咳痰",
					options: [
						{ key: "none", label: "无咳痰" },
						{ key: "white_foam", label: "白色泡沫" },
						{ key: "yellow_thick", label: "黄色黏稠" },
						{ key: "bloody", label: "血性" },
						{ key: "purulent", label: "脓性" },
						{ key: "large_amount", label: "大量" },
					],
					columns: 3,
				},
				{
					key: "sputum_detail",
					type: "input",
					label: "咳痰量/色/味",
					placeholder: "如：每日约50ml，黄色，无异味",
				},
				{
					key: "dyspnea",
					type: "radio",
					label: "呼吸困难",
					options: ["无", "劳力性", "静息时", "端坐呼吸"],
				},
				{
					key: "lung_auscultation",
					type: "textarea",
					label: "肺部听诊",
					placeholder: "描述呼吸音、啰音分布及性质...",
				},
			],
		},
		{
			key: "circulatory",
			label: "循环系统评估",
			icon: "Heart",
			collapsible: true,
			items: [
				{
					key: "heart_rate",
					type: "input",
					label: "心率",
					unit: "次/分",
					placeholder: "60-100",
				},
				{
					key: "heart_rhythm",
					type: "radio",
					label: "心律",
					options: ["齐", "不齐", "早搏"],
				},
				{
					key: "edema",
					type: "select",
					label: "水肿",
					options: ["", "无", "轻度", "中度", "重度"],
					placeholder: "请选择",
				},
				{
					key: "peripheral_circulation",
					type: "radio",
					label: "末梢循环",
					options: ["温暖", "凉", "发绀"],
				},
				{
					key: "skin_color",
					type: "select",
					label: "皮肤颜色",
					options: ["", "正常", "苍白", "潮红", "黄染", "发绀"],
					placeholder: "请选择",
				},
			],
		},
		{
			key: "pain",
			label: "疼痛评估",
			icon: "Zap",
			collapsible: true,
			items: [
				{
					key: "pain_location",
					type: "input",
					label: "疼痛部位",
					placeholder: "如：胸骨后、左上腹...",
				},
				{
					key: "pain_nature",
					type: "select",
					label: "疼痛性质",
					options: [
						"",
						"无痛",
						"钝痛",
						"锐痛",
						"胀痛",
						"烧灼痛",
						"绞痛",
						"刺痛",
						"压榨样",
					],
					placeholder: "请选择",
				},
				{
					key: "pain_score",
					type: "input",
					label: "疼痛评分",
					unit: "0-10",
					placeholder: "0为无痛，10为最剧烈",
				},
				{
					key: "pain_factors",
					type: "textarea",
					label: "加重/缓解因素",
					placeholder: "描述何种情况下加重或缓解...",
				},
			],
		},
		{
			key: "psychosocial",
			label: "心理社会评估",
			icon: "Smile",
			collapsible: true,
			items: [
				{
					key: "mood",
					type: "select",
					label: "情绪状态",
					options: ["", "平稳", "焦虑", "抑郁", "恐惧", "易激惹"],
					placeholder: "请选择",
				},
				{
					key: "disease_awareness",
					type: "radio",
					label: "对疾病认知",
					options: ["了解", "部分了解", "不了解"],
				},
				{
					key: "family_support",
					type: "radio",
					label: "家庭支持",
					options: ["良好", "一般", "缺乏"],
				},
				{
					key: "economic_concern",
					type: "radio",
					label: "经济顾虑",
					options: ["无", "轻度", "明显"],
				},
			],
		},
		{
			key: "risk",
			label: "风险评估",
			icon: "ShieldAlert",
			collapsible: true,
			items: [
				{
					key: "fall_risk",
					type: "select",
					label: "跌倒风险",
					options: ["", "低", "中", "高"],
					placeholder: "请选择",
					required: true,
				},
				{
					key: "pressure_ulcer_risk",
					type: "select",
					label: "压疮风险",
					options: ["", "低", "中", "高"],
					placeholder: "请选择",
					required: true,
				},
				{
					key: "self_care_score",
					type: "input",
					label: "自理能力评分",
					unit: "分",
					placeholder: "Barthel指数",
				},
				{
					key: "allergy",
					type: "input",
					label: "过敏史",
					placeholder: "药物/食物/其他过敏原",
				},
			],
		},
		{
			key: "nursing_plan",
			label: "护理计划",
			icon: "ClipboardList",
			collapsible: true,
			items: [
				{
					key: "nursing_diagnosis",
					type: "textarea",
					label: "护理诊断",
					placeholder: "列出主要护理诊断（PES格式）...",
				},
				{
					key: "nursing_goals",
					type: "textarea",
					label: "护理目标",
					placeholder: "短期和长期护理目标...",
				},
				{
					key: "nursing_measures",
					type: "textarea",
					label: "护理措施",
					placeholder: "具体护理措施及依据...",
				},
				{
					key: "health_education",
					type: "textarea",
					label: "健康教育",
					placeholder: "需向患者/家属进行的健康教育内容...",
				},
			],
		},
	],
};
